services:
  mypostgres:
    image: mypostgres:16.4
    restart: always
    user: postgres
    secrets:
      - db-web-password
      - db-springsession-password
    #    volumes:
    #      - /var/data/docker/db/postgresql:/opt/mypostgres/data
    networks:
      - backend
    ports:
      - "5432:5432"
    build:
#      dockerfile: dockerfiles/mypostgres.2404.Dockerfile
      target: mypostgres
      args:
        - POSTGRES_UID=110
        - POSTGRES_GID=119

  myldap:
    image: myslapd:2.6.7
    restart: always
    user: openldap
    secrets:
      - ldap-password
    networks:
      - backend
    ports:
      - "389:389"
#    volumes:
#      - /var/data/docker/openldap/etienda:/opt/myslapd/etienda/data
    build:
#      dockerfile: dockerfiles/myldap.2404.Dockerfile
      target: myslapd
      args:
        - OPENLDAP_UID=109
        - OPENLDAP_GID=117

  messengerapp:
    image: messengerapp:1.0
    user: webappuser
    secrets:
      - jasypt-password
    depends_on:
      - mypostgres
      - myldap
    networks:
      - backend
    ports:
      - "8082:8082"
    env_file:
      - webapp.env
#    volumes:
#      - /mnt/c/Users/I849921/IdeaProjects:/opt/webapp
    build:
#      dockerfile: dockerfiles/myjava.21.Dockerfile
      target: messengerapp
      args:
        - DOCKER_GID=999

  usuarioapp:
    image: usuarioapp:1.0
    user: webappuser
#    entrypoint: /bin/bash
    secrets:
      - jasypt-password
    depends_on:
      - mypostgres
      - myldap
      - messengerapp
    networks:
      - backend
    ports:
      - "8081:8081"
    env_file:
      - webapp.env
    build:
      #      dockerfile: dockerfiles/myjava.21.Dockerfile
      target: usuarioapp
      args:
        - DOCKER_GID=999

  testcontainer:
    image: testcontainer:1.0
    user: webappuser
    entrypoint: /bin/bash
    secrets:
      - jasypt-password
    depends_on:
      - mypostgres
      - myldap
    networks:
      - backend
    env_file:
      - webapp.env
#    volumes:
#      - /mnt/c/Users/I849921/IdeaProjects:/opt/webapp
    build:
      target: testcontainer
      args:
        - DOCKER_GID=999

networks:
  backend:

secrets:
  db-web-password:
    file: private/db-web-password.txt
  db-springsession-password:
    file: private/db-springsession-password.txt
  ldap-password:
    file: ./private/ldap-password.txt
  jasypt-password:
    file: ./private/jasypt-password.txt
