services:
  mypostgres:
    image: mypostgres:16.4
    restart: always
    user: postgres
    build:
      dockerfile: dockerfiles/mypostgres.2404.Dockerfile
      args:
        - POSTGRES_UID=110
        - POSTGRES_GID=119
    secrets:
      - db-password
    volumes:
      - /var/data/docker/db/postgresql:/opt/mypostgres/data
    ports:
      - "5432:5432"
  myldap:
    image: myslapd:2.6.7
    restart: always
    user: openldap
    secrets:
      - ldap-password
    volumes:
      - /var/data/docker/openldap/etienda:/opt/myslapd/etienda/data
    build:
      dockerfile: dockerfiles/myldap.2404.Dockerfile
      args:
        - OPENLDAP_UID=109
        - OPENLDAP_GID=117
    ports:
      - "389:389"
  myjava:
    image: myjava:21.0.4
    user: javauser
    build:
      dockerfile: dockerfiles/myjava.21.Dockerfile
      args:
        - DOCKER_GID=999
secrets:
  db-password:
    file: ./private/db-password.txt
  ldap-password:
    file: ./private/ldap-password.txt
