#tomcat
server.port=${PORT_MESSENGER}

#Email
spring.mail.default-encoding=UTF-8
spring.mail.port=${SMTP_EMAIL_PORT}
spring.mail.host=${SMTP_EMAIL_HOST}
spring.mail.username=${SMTP_EMAIL_USERNAME}
spring.mail.password=${SMTP_EMAIL_ENC_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.smtp.auth=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false
#spring.mail.test-connection=false
#spring.mail.properties.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
