seo:
  url: https://${WEBAPP_PUBLIC_ADDRESS}:${WEBAPP_PUBLIC_PORT}
  signIn: /signin.html #QUERY_PARAMETER: redirect //signin.html?redirect={currentUri}
  logout: /logout
  home:
    file: /home.html
    uri: ${seo.url}${seo.home.file}
  user:
    all: users.html
    file: user.html
    folder: /user
    find:
      file: /find.html/{username}
      path: ${seo.user.folder}${seo.user.find.file}
    test:
      file: /test.html/{username}
      path: ${seo.user.folder}${seo.user.test.file}
  manage:
    file: /manage.html
    folder: /manage
    user:
      file: /user.html
      path: ${seo.manage.folder}${seo.manage.user.file.file}
    company:
      folder: ${seo.manage.folder}/company
      all: ${seo.manage.folder}/company.html
      create: ${seo.manage.company.folder}/create.html
      find: ${seo.manage.company.folder}/{vanityUrl}.html
    test:
      file: /test.html
      path: ${seo.manage.folder}${seo.manage.test.file}

api:
  kc:
    url: https://${KC_PUBLIC_ADDRESS}:${WEBAPP_PUBLIC_PORT}
    realm:
      name: etrealm
      file: /realms/${api.kc.realm.name}
      uri: ${api.kc.url}${api.kc.realm.file}
      account: ${api.kc.realm.uri}/account
      token:
        file: /protocol/openid-connect/token
        uri: ${api.kc.realm.uri}${api.kc.realm.token.file}
      certs: ${api.kc.realm.uri}/protocol/openid-connect/certs
      admin:
        file: /admin${api.kc.realm.file}
        uri: ${api.kc.url}${api.kc.realm.admin.file}
        user:
          create: ${api.kc.realm.admin.uri}/users
          byUsername: ${api.kc.realm.admin.uri}/users?username={username}&exact=true
          byUserId: ${api.kc.realm.admin.uri}/users/{userId}
        role:
          users: ${api.kc.realm.admin.uri}/roles/{roleName}/users
  kcUser:
    server: http://etuser:${PORT_USUARIO}
    folder: /api/v0/user

    # Find current logged user
    find:
      file: find
      uri: ${api.kcUser.uri.folder}/${api.kcUser.find.file}
    token:
      file: token
      uri: ${api.kcUser.uri.folder}/${api.kcUser.token.file}
      path: ${api.kcUser.folder}/${api.kcUser.token.file}
    actuator:
      path: /actuator
      uri: ${api.kcUser.server}${api.kcUser.actuator.path}
      health:
        file: health
        uri: ${api.kcUser.actuator.uri}/${api.kcUser.actuator.health.file}
    login:
      file: login
      uri: ${api.kcUser.uri.folder}/${api.kcUser.login.file}
    isUsernameValid:
      file: /isUsernameValid/{username}
      uri: ${api.kcUser.uri.folder}${api.kcUser.isUsernameValid.file}
    isUserIdValid:
      file: /isUserIdValid/{userId}
      uri: ${api.kcUser.uri.folder}${api.kcUser.isUserIdValid.file}
    file:
      findEmailAddress: /findEmailAddress/{userId}
      create: /create
      userIdExists: /userIdExists/{userId}
      enable: /enable/{userId}
      delete: /delete/{userId}
    uri:
      folder: ${api.kcUser.server}${api.kcUser.folder}
      findEmailAddress: ${api.kcUser.uri.folder}${api.kcUser.file.findEmailAddress}
      create: ${api.kcUser.uri.folder}${api.kcUser.file.create}
      userIdExists: ${api.kcUser.uri.folder}${api.kcUser.file.userIdExists}
      enable: ${api.kcUser.uri.folder}${api.kcUser.file.enable}
      delete: ${api.kcUser.uri.folder}${api.kcUser.file.delete}
    path:
      login: ${api.kcUser.folder}/${api.kcUser.login.file}
      find: ${api.kcUser.folder}/${api.kcUser.find.file}
      delete: ${api.kcUser.folder}${api.kcUser.file.delete}
  schema:
    port: 8083
    url: http://etschema:${api.schema.port}
    root: /api/v0/schema
    uri: ${api.schema.url}${api.schema.root}
    helloAll: helloAll
    helloUser: helloUser
    login:
      file: login
      uri: ${api.schema.uri}/${api.schema.login.file}

    create:
    # ACTION: Create new database item
    # METHOD: post
    # QUERY PARAMETERS:
    # - {clazzName}: Name of class encoded with Base64
    # BODY: Schema item in JSON representation
    # RETURNS:
    # - Code: 200 on success
    # - Body: Schema item in JSON representation includes itemId and owner
    # ERRORS:
    # - 400
    # - 401
    # - 403
    # - 500
      file: create
      path: ${api.schema.create.file}?clase={clazzName}
      uri: ${api.schema.uri}/${api.schema.create.path}

    isItemValid:
    # ACTION: Find if DbItem exists, and it is valid
    # METHOD: GET
    # PATH VARIABLES:
    # - id: Type: Long | exact id of the DbItem
    # BODY: void
    # SUCCESS:
    # - Code: 200
    # - Body: com.laetienda.model.schema.DbItem
    # ERRORS:
    # - 400: Item id is not "Long" type.
    # - 401: User does not have read permissions.
    # - 403:
    # - 404: Item does not exist
    # - 500:
      file: isItemValid/{id}
      uri: ${api.schema.uri}/${api.schema.isItemValid.file}?clase={clazzName}

    findAll:
    # ACTION: Find all items where that user can read
    # METHOD: GET
    # QUERY PARAMETERS:
    # - clazzName: Name of class encoded with Base64
    # ON SUCCESS:
    # - Code: 200
    # - Body: List<T>
    # ERRORS:
    # - 400:
    # - 401:
    # - 403:
    # - 404:
    # - 500:
      file: find/all
      path: ${api.schema.findAll.file}?clazzNameEncoded={clazzName}
      uri: ${api.schema.uri}/${api.schema.findAll.path}

    find:
      file: find
      path: ${api.schema.find.file}?clase={clazzName}
      uri: ${api.schema.uri}/${api.schema.find.path}
    findById:
      file: find/{id}
      uri: ${api.schema.uri}/${api.schema.findById.file}?clase={clazzName}
    findSingleResultByQuery:
      file: findSingleResultByQuery
      uri: ${api.schema.uri}/${api.schema.findSingleResultByQuery.file}?clase={clazzName}
    findByQuery:
      file: findByQuery
      uri: ${api.schema.uri}/${api.schema.findByQuery.file}?clase={clazzEncoded}
    delete:
      file: delete
      path: ${api.schema.delete.file}?clase={clazzName}
      uri: ${api.schema.uri}/${api.schema.delete.path}
    deleteById:
      file: delete/{id}
      uri: ${api.schema.uri}/${api.schema.deleteById.file}?clase={clazzName}

    deleteUserById:
    # ACTION: Remove user from item reader and editor.
    # METHOD: DELETE
    # PATH VARIABLES:
    # - userId: id of user to be removed
    # ON SUCCESS:
    # - Code: 204 - no content
    # - Body: void
    # ERRORS:
    # - 401: Unauthorized - only same user can remove user, or user with role_manager
    # - 403: Forbidden - If user is owner of any item, or user belongs to any schema group.
      file: deleteUser/{userId}
      uri: ${api.schema.uri}/${api.schema.deleteUserById.file}

    update:
      file: update
      path: ${api.schema.update.file}?clase={clazzName}
      uri: ${api.schema.uri}/${api.schema.update.path}
    group:
      root: ${api.schema.root}/group
      file:
        findAll: /groups
        # ACTION: Find all groups where user is member or owner
        # METHOD: GET
        # ON SUCCESS:
        # - Code: 200
        # - Body: List<schema.DbGroup>
        # ERRORS:
        # - 400:
        # - 401:
        # - 403:
        # - 404:
        # - 500:

        findByName: /group/findByName/{groupName}
        update: /group/{groupId}/update
        delete: /group/{groupId}/delete
        orphans: /group/orphans
        member:
          add: /group/{groupId}/member/add/{userId}
          remove: /group/{groupId}/member/remove/{userId}
      uri:
        findAll: ${api.schema.uri}${api.schema.group.file.findAll}
        findByName: ${api.schema.uri}${api.schema.group.file.findByName}
        update: ${api.schema.uri}${api.schema.group.file.update}
        delete: ${api.schema.uri}${api.schema.group.file.delete}
        orphans: ${api.schema.uri}${api.schema.group.file.orphans}
        member:
          add: ${api.schema.uri}${api.schema.group.file.member.add}
          remove: ${api.schema.uri}${api.schema.group.file.member.remove}
  mail:
    url: http://etmail:${PORT_MESSENGER}
    folder: /api/v0/email
    file:
      test: test
      send: send
    uri:
      folder: ${api.mail.url}${api.mail.folder}
      test: ${api.mail.uri.folder}/${api.mail.file.test}
      send: ${api.mail.uri.folder}/${api.mail.file.send}
  company:
    url: http://etcompany:${PORT_COMPANY}
    folder: /api/v0/company
    uri: ${api.company.url}${api.company.folder}
    create: # METHOD: post | BODY: company | CODE: 200 | RESP: Company.class
      file: create
      uri: ${api.company.uri}/${api.company.create.file}
    isValid: # METHOD: get | CODE: 200 | RESP: string (CompanyId)
      file: isValid/{companyId}
      uri: ${api.company.uri}/${api.company.isValid.file}
    find: # METHOD: get | BODY: null | CODE: 200 | RESP: Company.class
      file: find/{id}
      uri: ${api.company.uri}/${api.company.find.file}
    findByName: # METHOD: get | BODY: null | CODE: 200 | RESP: Company.class
      file: findByName/{name}
      uri: ${api.company.uri}/${api.company.findByName.file}
    update: # METHOD: put | CODE: 200 | RESP: company
      file:
        name: update/{companyId}/name/{value} # BODY: null
        description: update/{companyId}/description # BODY: null
        content: update/{companyId} # BODY: Map<String, String>
      uri:
        name: ${api.company.uri}/${api.company.update.file.name}
        description: ${api.company.uri}/${api.company.update.file.description}
        content: ${api.company.uri}/${api.company.update.file.content}
    delete: # METHOD: delete | CODE: 204 | RESP: void
      file: delete/{id}
      uri: ${api.company.uri}/${api.company.delete.file}
    manager:
      file:
        add: /{companyId}/manager/add/{userId}
        remove: /{companyId}/manager/remove/{userId}
      uri:
        add: ${api.company.uri}${api.company.manager.file.add}
        remove: ${api.company.uri}${api.company.manager.file.remove}
    member:
      find:
        file: member/find/{companyId}/{userId}
        uri: ${api.company.uri}/${api.company.member.find.file}
      add:
        file: member/add/{companyId}/{userId}
        uri: ${api.company.uri}/${api.company.member.add.file}
      update:
        file: member/update
        uri: ${api.company.uri}/${api.company.member.update.file}
      delete:
        file: member/delete/{companyId}/{userId}
        uri: ${api.company.uri}/${api.company.member.delete.file}
    friend:
      file:
        find: friend/{companyId}/{userId}
        add: friend/add/{companyId}/{userId}
        accept: friend/accept/{companyId}/{userId}
        block: friend/block/{companyId}/{userId}
        unblock: friend/unblock/{companyId}/{userId}
      uri:
        find: ${api.company.uri}/${api.company.friend.file.find}
        add: ${api.company.uri}/${api.company.friend.file.add}
        accept: ${api.company.uri}/${api.company.friend.file.accept}
        block: ${api.company.uri}/${api.company.friend.file.block}
        unblock: ${api.company.uri}/${api.company.friend.file.unblock}